version: '3.9'

services:
  db:
    image: postgres:16
    container_name: wasm_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wasmdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: wasm_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://wasmuser:wasmpass@db:5432/wasmdb
    ports:
      - "8000:8000"

  web:
    build: ./web
    container_name: wasm_web
    depends_on:
      - api
    ports:
      - "8080:8000"

volumes:
  pgdata:
