version: '3.9'

services:
  db:
    image: postgres:16
    container_name: wasm_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - wasm_net
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    build: ./api
    container_name: wasm_api
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8000:8000"
    networks:
      - wasm_net
    env_file:
      - .env

  web:
    build: ./web
    container_name: wasm_web
    depends_on:
      - api
    ports:
      - "8080:8000"
    networks:
      - wasm_net
volumes:
  pgdata:

networks:
  wasm_net:
    driver: bridge
